Add csv_download_response_dict function
gamernetwork/gn-django pull request #109
Opened 2020-10-14 08:08 UTC by johnpooch

- [x] Is this Pull Request ready for review?
- [x] Do the tests pass?
- [x] Have the docs been updated?
- [x] Have any new settings been added?  Have they got comments?  Have they been added to the settings documentation page?

**What does this Pull Request do?**
Adds a new function for downloading a list of dicts as a CSV.

Behaves similarly to CSV download response but accepts a list of dicts.
Refactored response preparation step into _format_csv_response to reduce
duplication between the functions.

Adds tests coverage for new function.

**Are there new tests?**
Yes

**Any background context you want to provide?**
Part of my on-going work with CSV uploading and downloading. Passing in a list
of dicts can be easier than a list of lists depending on how your data is
structured.

2020-10-16 09:36 UTC, deains requested changes

2020-10-16 09:36 UTC, deains commented on gn_django/utils/http.py
> +    writer = csv.DictWriter(response, data[0].keys())
Should probably not assume that the first dict element has every key. Ideally you'd check every item in the dict to work out the headings, but that may be slow.

2020-10-16 09:36 UTC, deains commented on gn_django/utils/http.py
> +    writer = csv.DictWriter(response, data[0].keys())
Also should probably check that `data` is not empty.

2020-10-26 10:33 UTC, johnpooch commented on gn_django/utils/http.py
> +    writer = csv.DictWriter(response, data[0].keys())
It now gets every key from data. Keys are sorted alphabetically because otherwise we can't anticipate order. Have added a check fro empty data. Raises a `ValueError` if empty.

2020-10-26 15:28 UTC, deains approved these changes

2020-10-27 13:40 UTC, merged